<?php

return [
    'default' => [
        'id' => 1,
        'slug' => 'default',
        'name' => 'Default',
        'icon' => '/icons/default.svg',
        'prompt' => 'Write a compelling piece of content that is engaging, well-structured, and optimized for the target audience. Maintain a clear and natural flow, use persuasive language where needed, and ensure readability. Keep the tone appropriate for the context, and include a strong call to action if necessary.',
        'variables' => [],
    ],
    'ad-copy' => [
        'id' => 2,
        'slug' => 'ad-copy',
        'name' => 'Ad copy',
        'icon' => '/icons/ad-copy.svg',
        'prompt' => 'Generate a high-converting ad copy for {adTopic}. The platform is {adPlatform}, and the target audience is {targetAudience}. Emphasize {keyBenefits} and include a strong call to action. Return only the generated ad copy without any explanations or additional text.',
        'variable' => 'variable',
        'adTopic' => 'adTopic',
        'adPlatform' => 'adPlatform',
        'targetAudience' => 'targetAudience',
        'keyBenefits' => 'keyBenefits'
    ],
    'marketing-content' => [
        'id' => 3,
        'slug' => 'marketing-content',
        'name' => 'Marketing Content',
        'icon' => '/icons/marketing-content.svg',
        'prompt' => 'Write a {contentType} about {contentTopic}. The tone should be {toneStyle}, and the content should focus on {keyFocus}. Return only the content without any explanations or additional text.',
        'variable' => 'variable',
        'contentType' => 'contentType',
        'contentTopic' => 'contentTopic',
        'toneStyle' => 'toneStyle',
        'keyFocus' => 'keyFocus',
    ],
    'email-marketing' => [
        'id' => 4,
        'slug' => 'email-marketing',
        'name' => 'Email Marketing',
        'icon' => '/icons/email-marketing.svg',
        'prompt' => 'Write an email for {emailPurpose}. The audience is {targetAudience}, and the tone should be {emailTone}. Include a strong call to action.',
        'variable' => 'variable',
        'emailPurpose' => 'emailPurpose',
        'targetAudience' => 'targetAudience',
        'emailTone' => 'emailTone',
    ],
    'social-media-content' => [
        'id' => 5,
        'slug' => 'social-media-content',
        'name' => 'Social Media Content',
        'icon' => '/icons/social-media-content.svg',
        'prompt' => 'Generate a {socialPlatform} post about {postTopic}Generate a {socialPlatform} post about {postTopic}. The goal is {postGoal}, and the tone should be {postTone}. Keep it within {characterLimit}. Return only the post without any explanations or additional text.',
        'variable' => 'variable',
        'socialPlatform' => 'socialPlatform',
        'postTopic' => 'postTopic',
        'postGoal' => 'postGoal',
        'postTone' => 'postTone',
        'characterLimit' => 'characterLimit',


    ],
    'seo-content' => [
        'id' => 6,
        'slug' => 'seo-content',
        'name' => 'SEO Content',
        'icon' => '/icons/seo-content.svg',
        'prompt' => "Generate an SEO-friendly {contentType} for {seoTopic}. Include {keywordsList} and keep it {contentLength}. Ensure it's optimized for search engines. Return only the content without any explanations or additional text.",
        'variable' => 'variable',
        'contentType' => 'contentType',
        'seoTopic' => 'seoTopic',
        'keywordsList' => 'keywordsList',
        'contentLength' => 'contentLength',
    ],
    'storytelling-branding' => [
        'id' => 7,
        'slug' => 'storytelling-branding',
        'name' => 'Storytelling Branding',
        'icon' => '/icons/storytelling-branding.svg',
        'prompt' => 'Write a {contentType} for {companyName}. The brand tone is {brandTone}, and the goal is to resonate with {targetAudience}. Return only the text without any explanations or additional text.',
        'variable' => 'variable',
        'contentType' => 'contentType',
        'companyName' => 'companyName',
        'brandTone' => 'brandTone',
        'targetAudience' => 'targetAudience',
    ],
    'ai-text-analysis-enhancement' => [
        'id' => 8,
        'slug' => 'ai-text-analysis-enhancement',
        'name' => 'AI Text Analysis',
        'icon' => '/icons/ai-text-analysis-enhancement.svg',
        'prompt' => 'Analyze this text and suggest an improved version with better tone, clarity, and SEO optimization: {originalText}. Return only the improved version without any explanations or additional text.',
        'variable' => 'variable',
        'originalText' => 'originalText',
    ],
    'personalized-messages-communication' => [
        'id' => 9,
        'slug' => 'personalized-messages-communication',
        'name' => 'Personalized Communication',
        'icon' => '/icons/personalized-messages-communication.svg',
        'prompt' => 'Generate a professional LinkedIn connection message for {recipientProfession}. The tone should be {messageTone}, and the purpose is {connectionPurpose}. Return only the message without any explanations or additional text.',
        'variable' => 'variable',
        'recipientProfession' => 'recipientProfession',
        'messageTone' => 'messageTone',
        'connectionPurpose' => 'connectionPurpose',
    ],
    'hyper-personalized-sales-copy' => [
        'id' => 10,
        'slug' => 'hyper-personalized-sales-copy',
        'name' => 'Hyper Personalized Sales Copy',
        'icon' => '/icons/hyper-personalized-sales-copy.svg',
        'prompt' => 'Create a high-converting sales pitch for {productOrService}. The target audience is {targetAudience}. Highlight their pain points and explain how this solution benefits them. Keep the tone {toneStyle}. Return only the sales pitch without any explanations or additional text.',
        'variable' => 'variable',
        'productOrService' => 'productOrService',
        'targetAudience' => 'targetAudience',
        'toneStyle' => 'toneStyle',
    ],

    'youtube-video-content' => [
        'id' => 11,
        'slug' => 'youtube-video-content',
        'name' => 'YouTube Video Content',
        'icon' => '/icons/youtube-video-content.svg',
        'prompt' => 'Write a YouTube script for a video about {videoTopic}. The video should be {videoLength}, and the tone should be {toneStyle}. Include a strong hook and a call to action at the end.',
        'variable' => 'variable',
        'videoTopic' => 'videoTopic',
        'videoLength' => 'videoLength',
        'toneStyle' => 'toneStyle',
    ],
    'ai-chatbot-customer-support-messages' => [
        'id' => 12,
        'slug' => 'ai-chatbot-customer-support-messages',
        'name' => 'Ai Chatbot Customer Support',
        'icon' => '/icons/ai-chatbot-customer-support-messages.svg',
        'prompt' => 'Generate a customer support response for a user asking about {customerQuery}. Keep the response {responseTone} and include troubleshooting steps.',
        'variable' => 'variable',
        'customerQuery' => 'customerQuery',
        'responseTone' => 'responseTone',
    ],
    'e-commerce-dropshipping' => [
        'id' => 13,
        'slug' => 'e-commerce-dropshipping',
        'name' => 'E-Commerce Dropshipping',
        'icon' => '/icons/e-commerce-dropshipping.svg',
        'prompt' => 'Write a product description for {productTitle}. The description should be {descriptionFormat}, emphasize {keyFeatures}, and be written in {writingStyle} style. Return only the product description without any explanations or additional text.',
        'variable' => 'variable',
        'productTitle' => 'productTitle',
        'descriptionFormat' => 'descriptionFormat',
        'keyFeatures' => 'keyFeatures',
        'writingStyle' => 'writingStyle',
    ],
    'newsletter-community-content' => [
        'id' => 14,
        'slug' => 'newsletter-community-content',
        'name' => 'Newsletter Community Content',
        'icon' => '/icons/newsletter-community-content.svg',
        'prompt' => 'Write a newsletter introduction for {newsletterTopic}. The audience is {audienceGroup}, and the goal is to {newsletterGoal}. Keep the tone {toneOfVoice}.',
        'variable' => 'variable',
        'newsletterTopic' => 'newsletterTopic',
        'audienceGroup' => 'audienceGroup',
        'newsletterGoal' => 'newsletterGoal',
        'toneOfVoice' => 'toneOfVoice',
    ],
    'ai-pr-outreach' => [
        'id' => 15,
        'slug' => 'ai-pr-outreach',
        'name' => 'AI Outreach',
        'icon' => '/icons/ai-pr-outreach.svg',
        'prompt' => 'Write a press release for {announcementTopic}. It should include {keyInformation} and have a {toneStyle} tone.',
        'variable' => 'variable',
        'announcementTopic' => 'announcementTopic',
        'keyInformation' => 'keyInformation',
        'toneStyle' => 'toneStyle',
    ],
    'hr-recruitment' => [
        'id' => 16,
        'slug' => 'hr-recruitment',
        'name' => 'HR Recruitment',
        'icon' => '/icons/hr-recruitment.svg',
        'prompt' => 'Write a job posting for {jobTitle}. It should highlight {keyHighlights} and be engaging for potential candidates. Return only the job posting without any explanations or additional text.',
        'variable' => 'variable',
        'jobTitle' => 'jobTitle',
        'keyHighlights' => 'keyHighlights',
    ],
    'tiktok-viral-content-hooks' => [
        'id' => 17,
        'slug' => 'tiktok-viral-content-hooks',
        'name' => 'TikTok Viral Content Hooks',
        'icon' => '/icons/tiktok-viral-content-hooks.svg',
        'prompt' => 'Generate 5 viral TikTok video ideas for {videoTheme}. Each idea should have a strong hook and be designed for {videoObjective}. Return only the ideas without any explanations or additional text.',
        'variable' => 'variable',
        'videoTheme' => 'videoTheme',
        'videoObjective' => 'videoObjective',
    ],
];
